#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 3
#SBATCH -t 01:00:00 
#SBATCH -J mummer_genome_alignment
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_20221115
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_20221115
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

O11="/proj/sllstore2017063/y_chromosome/rawdata/O11_data/O11.fasta"
ref="/proj/sllstore2017063/y_chromosome/D_willistoni_ref_genome/ncbi_dataset/data/GCF_018902025.1/*fasta"
res="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11"

module load bioinfo-tools MUMmer

nucmer -t 3 -p ${res}/mummer_O11_willistoni $ref $O11
