#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 2
#SBATCH -t 10:00:00
#SBATCH -J cov_M
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/cov_M
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/cov_M
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

#male files
cd /crex/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/08_RNA_mapping/

module load bioinfo-tools samtools BEDTools/2.29.2

samtools sort m_star_merged.bam > m_star_merged_sorted.bam
bedtools genomecov -d -pc -ibam m_star_merged_sorted.bam > m_star_cov


