#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 2
#SBATCH -t 10:00:00
#SBATCH -J cov_F
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/cov_F
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/cov_F
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

module load bioinfo-tools samtools BEDTools/2.29.2

#female files
cd /crex/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/08_RNA_mapping/star_output
cd /crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/06_assembly_eval

samtools sort f_star_merged.bam > f_star_merged_sorted.bam
bedtools genomecov -d -pc -ibam f_star_merged_sorted.bam > f_star_cov

