#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 4
#SBATCH -t 01:00:00
#SBATCH -J flye_generategenome
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/flye_generategenome
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/flye_generategenome
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

GENOME_FILE="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/05_assemblies/flye_assembler_nanopore/*.fasta"
GENOME_IND="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/08_RNA_mapping/genome_index"

module load bioinfo-tools star

star --runThreadN 8 --runMode genomeGenerate \
--genomeDir $GENOME_IND \
--genomeFastaFiles $GENOME_FILE
 
