#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 4
#SBATCH -t 10:00:00
#SBATCH -J merge_F
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/merge_F
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/merge_F
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

#STAR_DIR="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/08_RNA_mapping/star_output"
STAR_DIR="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/06_assembly_eval"
module load bioinfo-tools samtools

BAM_FILES="${STAR_DIR}/*WT-F*.sortedByCoord.out.bam"

samtools merge -f -o ${STAR_DIR}/f_star_merged.bam -@ 3 ${BAM_FILES}
