#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 10
#SBATCH -t 20:00:00
#SBATCH -J blastn_genomealignment
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/blastn_log
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/blastn_log
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

module load bioinfo-tools blast

O11="/proj/sllstore2017063/y_chromosome/rawdata/O11_data/*fasta"
ref="/proj/sllstore2017063/y_chromosome/D_willistoni_ref_genome/ncbi_dataset/data/GCF_018902025.1/*.fasta"
OUTDIR="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res"

cd $SNIC_TMP

blastn -num_threads 10 -query $O11 -subject $ref -out ${OUTDIR}/blastn_D_paulistorum_willistoni.out -outfmt 6
