#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 3
#SBATCH -t 07:00:00
#SBATCH -J mummer_CANU
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_CANU
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_CANU

SUB="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/05_assemblies/flye_assembler_nanopore_Canu_nosecondary/assembly.fasta"
REF="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/04_extract_putative_Y/CANU-PY.fasta"
RES_DIR="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/06_assembly_eval/mummer"

module load bioinfo-tools MUMmer

#nucmer -t 3 -p ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment $REF $SUB

delta-filter -i 80 -l 10000 ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment.delta > ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment_filtered.delta

#show-coords -TrH ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment_filtered.delta > ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment_show_coords.out

#awk -F'\t' '{print $8, $1, $2, $9, $7}' ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment_show_coords.out > ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment_show_coords.bed

mummerplot --png -p ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_filtered_10000 -l ${RES_DIR}/CANU-PY_CANU-FLYE-DCA_alignment_filtered.delta

rm ${RES_DIR}/*plot ${RES_DIR}/*coords.out ${RES_DIR}/*.gp ${RES_DIR}/*.filter
