#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 1
#SBATCH -t 00:01:00
#SBATCH -J mummer_O11_wil
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_O11_wil_20221122
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_O11_wil_20221122
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

SUB="/proj/sllstore2017063/y_chromosome/rawdata/O11_data/O11.fasta"
REF="/proj/sllstore2017063/y_chromosome/D_willistoni_ref_genome/ncbi_dataset/data/GCF_018902025.1/*fasta"
RES_DIR="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11"
RES_DIR2="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11/other_files"
MUMMER_FILE="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11/O11_wil_alignment.delta"

module load bioinfo-tools MUMmer

#nucmer -t 3 -p ${RES_DIR}/O11_wil_alignment $REF $SUB

#delta-filter -i 80 -l 500 $MUMMER_FILE > ${RES_DIR}/O11_wil_alignment_filtered.delta

#show-coords -TrH ${RES_DIR}/O11_wil_alignment_filtered.delta > ${RES_DIR}/O11_wil_alignment_show_coords.out

#awk -F'\t' '{print $8, $1, $2, $9, $7}' ${RES_DIR}/O11_wil_alignment_show_coords.out > ${RES_DIR}/O11_wil_alignment_show_coords.bed

mummerplot --png -p ${RES_DIR}/mummerplot/mummerplot_O11_wil_filtered -R $REF -q $SUB ${RES_DIR2}//O11_wil_alignment_filtered.delta

