#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 3
#SBATCH -t 03:00:00
#SBATCH -J mummer_CANU_NDN
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_CANU_NDN
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_CANU_NDN

SUB="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/05_assemblies/flye_assembler_nanopore_Canu_nosecondary/assembly.fasta"
REF="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/05_assemblies/flye_assembler_nanopore/*.fasta"
RES_DIR="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/06_assembly_eval/mummer"

module load bioinfo-tools MUMmer

#nucmer -t 3 -p ${RES_DIR}/CANU-NDN_alignment $REF $SUB

delta-filter -i 80 -l 6000 ${RES_DIR}/CANU-NDN_alignment.delta > ${RES_DIR}/CANU-NDN_alignment_filtered.delta

#show-coords -TrH ${RES_DIR}/CANU-NDN_alignment_filtered.delta > ${RES_DIR}/CANU-NDN_alignment_show_coords.out

#awk -F'\t' '{print $8, $1, $2, $9, $7}' ${RES_DIR}/CANU-NDN_alignment_show_coords.out > ${RES_DIR}/CANU-NDN_alignment_show_coords.bed

mummerplot --png -p ${RES_DIR}/CANU-NDN_filtered_6000 -l ${RES_DIR}/CANU-NDN_alignment_filtered.delta

rm ${RES_DIR}/*plot ${RES_DIR}/*coords.out ${RES_DIR}/*.gp ${RES_DIR}/*.filter
