#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 3
#SBATCH -t 01:10:00
#SBATCH -J mummer_y_new_put
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_y_new_put
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_y_new_put
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

RES_DIR="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11"

module load bioinfo-tools MUMmer

nucmer --mum -t 3 -p ${RES_DIR}/y_put_mummer/y2_put_alignment ${RES_DIR}/y_contigs_wil.fasta ${RES_DIR}/y_contigs_O11_genefishing.fasta

delta-filter -i 80 -l 3000 ${RES_DIR}/y_put_mummer/y2_put_alignment.delta > ${RES_DIR}/y_put_mummer/y2_put_alignment_filtered.delta

show-coords -TrH ${RES_DIR}/y_put_mummer/y2_put_alignment_filtered.delta > ${RES_DIR}/y2_put_mummer/y_put_alignment_show_coords.out

awk -F'\t' '{print $8, $1, $2, $9, $7}' ${RES_DIR}/y_put_mummer/y2_put_alignment_show_coords.out > ${RES_DIR}/y_put_mummer/y2_put_alignment_show_coords.bed

mummerplot --png -p ${RES_DIR}/mummerplot/mummerplot_y2_put_filtered2 -l ${RES_DIR}/y_put_mummer/y2_put_alignment_filtered.delta -R ${RES_DIR}/y_contigs_wil.fasta
