#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 3
#SBATCH -t 01:00:00 
#SBATCH -J mummer_wil_O11_20221121
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_wil_switched_20221117
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_wil_switched_20221117
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

REF="/proj/sllstore2017063/y_chromosome/rawdata/O11_data/O11.fasta"
SUB="/proj/sllstore2017063/y_chromosome/D_willistoni_ref_genome/ncbi_dataset/data/GCF_018902025.1/*fasta"
RES_DIR="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11"
MUMMER_FILE="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11/wil_O11_alignment.delta"

module load bioinfo-tools MUMmer

nucmer -t 3 -p ${RES_DIR}/wil_O11_alignment $REF $SUB

delta-filter -i 80 -l 500 $MUMMER_FILE > ${RES_DIR}/wil_O11_alignment_filtered.delta

show-coords -TrH ${RES_DIR}/wil_O11_alignment_filtered.delta > ${RES_DIR}/wil_O11_alignment_show_coords.out

awk -F'\t' '{print $8, $1, $2, $9, $7}' ${RES_DIR}/wil_O11_alignment_show_coords.out > ${RES_DIR}/wil_O11_alignment_show_coords.bed
