#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 3
#SBATCH -t 07:00:00
#SBATCH -J mummer_canuflye
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_canuflye
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/mummer_canuflye

SUB="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/05_assemblies/flye_assembler_nanopore_Canu_nosecondary/assembly.fasta"
REF="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11//y_contigs_wil.fasta"
RES_DIR="/crex/proj/sllstore2017063/y_chromosome/nobackup/results/O11_Canu_res/06_assembly_eval/mummer"

module load bioinfo-tools MUMmer

#nucmer -t 3 -p ${RES_DIR}/wil_alignment $REF $SUB

delta-filter -i 80 -l 3500 ${RES_DIR}/wil_alignment.delta > ${RES_DIR}/wil_alignment_filtered.delta

#show-coords -TrH ${RES_DIR}/wil_alignment_filtered.delta > ${RES_DIR}/wil_alignment_show_coords.out

#awk -F'\t' '{print $8, $1, $2, $9, $7}' ${RES_DIR}/wil_alignment_show_coords.out > ${RES_DIR}/wil_alignment_show_coords.bed

mummerplot --png -p ${RES_DIR}/wil_al_filtered_3500 -l ${RES_DIR}/wil_alignment_filtered.delta

rm ${RES_DIR}/*plot ${RES_DIR}/*coords.out ${RES_DIR}/*.gp ${RES_DIR}/*.filter
