#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 6
#SBATCH -t 02:00:00 
#SBATCH -J minimap_O11_wil
#SBATCH -o /proj/sllstore2017063/y_chromosome/nobackup/logs/minimap2_wil_20221117
#SBATCH -e /proj/sllstore2017063/y_chromosome/nobackup/logs/minimap2_wil_20221117
#SBATCH --mail-user kalle.99@live.com
#SBATCH --mail-type=FAIL,END

O11="/proj/sllstore2017063/y_chromosome/rawdata/O11_data/O11.fasta"
REF="/proj/sllstore2017063/y_chromosome/D_willistoni_ref_genome/ncbi_dataset/data/GCF_018902025.1/*fasta"
RES_DIR="/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/genome_alignment_O11"

module load bioinfo-tools minimap2 samtools

minimap2 -ax asm5 -t 6 $REF $O11 | samtools view -h -b | samtools sort -o ${RES_DIR}/minimap2_O11_wil.bam

samtools index -b ${RES_DIR}/minimap2_O11_wil.bam

