#!/bin/bash -l
#SBATCH -A snic2022-22-721
#SBATCH -p core -n 1
#SBATCH -t 01:00:00 
#SBATCH -J job_name
#SBATCH --mail-user name.lastname@student.uu.se
#SBATCH --mail-type=FAIL,END

REF_GENOME='/proj/sllstore2017063/y_chromosome/rawdata/O11_data/*.fasta'
RES='/proj/sllstore2017063/y_chromosome/nobackup/results/D_paulistorum_O11_res/01_read_mapping'

module load bioinfo-tools bwa samtools

R1_PAIRED="/proj/sllstore2017063/y_chromosome/rawdata/O11_data/short_read_data/Sample*R1*"
bwa index ${REF_GENOME}

for i in $R1_PAIRED
do
	R2_PAIRED=${i/_R1.fastq.gz/_R2.fastq.gz}
	NAME=$(basename $i _R1.fastq.gz)
	bwa mem -t 16 ${REF_GENOME} ${i} ${R2_PAIRED} | samtools sort -o ${RES}/${NAME}.bam -
done
